### ISSUE TITLE
运行后机器人无回复

### ISSUE THREAD

**Issue by luoxue3145** [AstrBotDevs/AstrBot#147]
python 3.11.0
Windows 启动器
go-cqhttp 可以正常接收消息
测试机器人无回复
8046-7d792682142a)
![4521a0e873c58587c7dd94d0b9b0655](https://github.com/Soulter/AstrBot/assets/126536359/ce618063-3fcd-4ed5-85bf-2bc9ce3d899d)

私聊机器人：!myid   有反应 显示如下
![7feaeee3a8853cbd2acc51f871baddd](https://github.com/Soulter/AstrBot/assets/126536359/0679cddf-cb49-4eee-9184-45d2807f4b38)

![0c8944d8c30e3887dfb38cfbeb8e91b](https://github.com/Soulter/AstrBot/assets/126536359/603a6940-1401-431b-87d4-bd1f472658aa)

**Comment by Soulter** [comment]
👌 今晚会修一下`!myid`指令的这个问题

**Comment by Soulter** [comment]
已修复。
