### ISSUE TITLE
安装插件显示没权限，该如何做

### ISSUE THREAD

**Issue by animeic** [AstrBotDevs/AstrBot#153]
指令调用错误: 
你的身份组member没有权限安装插件

**Comment by Soulter** [comment]
你好，请在使用`myid`指令获得 user_id 之后将其填入下图：
<img width="1146" alt="image" src="https://github.com/Soulter/AstrBot/assets/37870767/ee98e32a-75a3-4184-aa50-131555a3e1b8">

**Comment by animeic** [comment]
好的
